#!/bin/sh

# Set these paths appropriately

BIN="/home/fante/Dropbox/Jupyter/Treetagger/bin"
CMD="/home/fante/Dropbox/Jupyter/Treetagger/cmd"
LIB="/home/fante/Dropbox/Jupyter/Treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

