#!/bin/sh

# Set these paths appropriately

BIN="/home/fante/Dropbox/Jupyter/Treetagger/bin"
CMD="/home/fante/Dropbox/Jupyter/Treetagger/cmd"
LIB="/home/fante/Dropbox/Jupyter/Treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
