#!/bin/sh

# Set these paths appropriately

BIN="/home/fante/Dropbox/Jupyter/Treetagger/bin"
CMD="/home/fante/Dropbox/Jupyter/Treetagger/cmd"
LIB="/home/fante/Dropbox/Jupyter/Treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
