#!/bin/sh

# Set these paths appropriately

BIN="/home/fante/Dropbox/Jupyter/Treetagger/bin"
CMD="/home/fante/Dropbox/Jupyter/Treetagger/cmd"
LIB="/home/fante/Dropbox/Jupyter/Treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

